const KEY='cc_site_content_v4';
let data=structuredClone(window.CC_DEFAULT_CONTENT); try{const s=localStorage.getItem(KEY);if(s)data=Object.assign(data,JSON.parse(s));}catch(e){}
const editor=document.getElementById('admin-editor'); const buttons=[...document.querySelectorAll('.admin-nav button')];
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function input(label,path,value,type='text'){return `<label class="field"><span>${label}</span>${type==='textarea'?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input type="${type}" data-path="${path}" value="${esc(value)}">`}</label>`}
function render(tab){buttons.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 if(tab==='site') editor.innerHTML=`<div class="admin-title"><p>HOME</p><h1>Contenido principal</h1><span>Todo esto se refleja en la landing.</span></div><div class="form-grid">${input('Anuncio superior','site.announcement',data.site.announcement)}${input('Eyebrow hero','site.heroEyebrow',data.site.heroEyebrow)}${input('Título hero','site.heroTitle',data.site.heroTitle,'textarea')}${input('Texto hero','site.heroText',data.site.heroText,'textarea')}${input('Botón principal','site.heroPrimary',data.site.heroPrimary)}${input('Botón secundario','site.heroSecondary',data.site.heroSecondary)}</div>`;
 if(tab==='courses') editor.innerHTML=`<div class="admin-title"><p>CURSOS</p><h1>Oferta académica</h1><span>Editá textos, duración, requisitos y estado de inscripción.</span></div><div class="repeat-list">${data.courses.map((c,i)=>`<details class="edit-card" ${i===0?'open':''}><summary><b>${esc(c.title)} ${esc(c.subtitle)}</b><span>${esc(c.status)}</span></summary><div class="form-grid">${input('Título',`courses.${i}.title`,c.title)}${input('Subtítulo',`courses.${i}.subtitle`,c.subtitle)}${input('Eyebrow',`courses.${i}.eyebrow`,c.eyebrow)}${input('Duración',`courses.${i}.duration`,c.duration)}${input('Modalidad',`courses.${i}.mode`,c.mode)}${input('Requisito',`courses.${i}.requirement`,c.requirement)}${input('Estado',`courses.${i}.status`,c.status)}${input('Texto corto',`courses.${i}.short`,c.short,'textarea')}${input('Beneficio principal',`courses.${i}.benefit`,c.benefit,'textarea')}${input('URL brochure',`courses.${i}.brochure`,c.brochure)}</div></details>`).join('')}</div>`;
 if(tab==='testimonials') editor.innerHTML=repeatEditor('TESTIMONIOS','Testimonios','testimonials',['name','course','quote','video']);
 if(tab==='news') editor.innerHTML=repeatEditor('NOVEDADES','Novedades','news',['date','tag','title','text','link']);
 if(tab==='services') editor.innerHTML=repeatEditor('SERVICIOS','Servicios','services',['eyebrow','title','text','cta']);
 if(tab==='community') editor.innerHTML=repeatEditor('COMUNIDAD','Comunidad','community',['label','title','text','link']);
 if(tab==='settings') editor.innerHTML=`<div class="admin-title"><p>CONFIGURACIÓN</p><h1>Enlaces y publicación</h1><span>Configurá los destinos generales del sitio.</span></div><div class="form-grid">${input('WhatsApp','site.whatsapp',data.site.whatsapp)}${input('Instagram','site.instagram',data.site.instagram)}${input('Aula virtual','site.aula',data.site.aula)}${input('Red de Actores','site.actores',data.site.actores)}${input('Red de Realizadores','site.realizadores',data.site.realizadores)}${input('Dirección','site.location',data.site.location)}</div><div class="admin-warning"><b>Importante sobre publicación</b><p>Esta versión guarda cambios en el navegador mediante LocalStorage. Sirve para editar y previsualizar sin tocar código. Para que los cambios se publiquen para todos los visitantes y desde cualquier dispositivo, conectá este panel a Supabase usando el archivo <code>supabase.sql</code> incluido.</p></div><div class="admin-actions"><button id="exportBtn">Exportar JSON</button><label class="import-label">Importar JSON<input id="importFile" type="file" accept="application/json"></label><button id="resetBtn" class="danger">Restaurar contenido inicial</button></div>`;
 bind(); }
function repeatEditor(kicker,title,key,fields){return `<div class="admin-title"><p>${kicker}</p><h1>${title}</h1><span>Editá el contenido que aparece en la landing.</span></div><div class="repeat-list">${data[key].map((item,i)=>`<details class="edit-card" ${i===0?'open':''}><summary><b>${esc(item.title||item.name||item.course||`${title} ${i+1}`)}</b><span>#${i+1}</span></summary><div class="form-grid">${fields.map(f=>input(f.charAt(0).toUpperCase()+f.slice(1),`${key}.${i}.${f}`,item[f]||'',f==='text'||f==='quote'?'textarea':'text')).join('')}</div></details>`).join('')}</div>`}
function setPath(obj,path,value){const parts=path.split('.');let cur=obj;parts.forEach((p,i)=>{if(i===parts.length-1)cur[p]=value;else cur=cur[p];});}
function bind(){document.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('input',()=>setPath(data,el.dataset.path,el.value)));
 const ex=document.getElementById('exportBtn');if(ex)ex.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cordoba-casting-content.json';a.click();};
 const imp=document.getElementById('importFile');if(imp)imp.onchange=e=>{const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(data));location.reload();}catch(err){alert('El archivo no es válido.')}};r.readAsText(e.target.files[0]);};
 const reset=document.getElementById('resetBtn');if(reset)reset.onclick=()=>{if(confirm('¿Restaurar el contenido inicial?')){localStorage.removeItem(KEY);location.reload();}};}
buttons.forEach(b=>b.onclick=()=>render(b.dataset.tab)); document.getElementById('saveBtn').onclick=()=>{localStorage.setItem(KEY,JSON.stringify(data));const b=document.getElementById('saveBtn');b.textContent='Guardado ✓';setTimeout(()=>b.textContent='Guardar cambios',1400);};render('site');
