let data=structuredClone(window.CC_DEFAULT_CONTENT),client=null;
const editor=document.getElementById('admin-editor'),login=document.getElementById('admin-login'),app=document.getElementById('admin-app');
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const input=(label,path,value,type='text')=>`<label class="field"><span>${label}</span>${type==='textarea'?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input type="${type}" data-path="${path}" value="${esc(value)}">`}</label>`;
async function init(){if(!window.CC_SUPABASE_URL||!window.CC_SUPABASE_ANON_KEY){document.getElementById('login-error').textContent='Falta configurar Supabase en config.js.';return}client=window.supabase.createClient(window.CC_SUPABASE_URL,window.CC_SUPABASE_ANON_KEY);const {data:{session}}=await client.auth.getSession();if(session)await authorize(session.user);}
async function authorize(user){const {data:admin}=await client.from('site_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(!admin){await client.auth.signOut();document.getElementById('login-error').textContent='Esta cuenta no tiene permisos de administrador.';return}const {data:row}=await client.from('site_content').select('content').eq('id','main').maybeSingle();if(row?.content)data=row.content;login.hidden=true;app.hidden=false;render('site');}
document.getElementById('login-form').addEventListener('submit',async e=>{e.preventDefault();const err=document.getElementById('login-error');err.textContent='';const {data:auth,error}=await client.auth.signInWithPassword({email:document.getElementById('login-email').value,password:document.getElementById('login-password').value});if(error){err.textContent='No se pudo iniciar sesión.';return}await authorize(auth.user)});
function setPath(obj,path,value){const p=path.split('.');let cur=obj;p.forEach((x,i)=>{if(i===p.length-1)cur[x]=value;else cur=cur[x]})}
function bind(){document.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('input',()=>setPath(data,el.dataset.path,el.value)))}
function repeatEditor(kicker,title,key,fields){return `<div class="admin-title"><p>${kicker}</p><h1>${title}</h1><span>Editá el contenido publicado.</span></div><div class="repeat-list">${data[key].map((item,i)=>`<details class="edit-card" ${i===0?'open':''}><summary><b>${esc(item.title||item.name||item.course||`${title} ${i+1}`)}</b><span>#${i+1}</span></summary><div class="form-grid">${fields.map(f=>input(f.label,`${key}.${i}.${f.key}`,item[f.key]||'',f.type||'text')).join('')}</div></details>`).join('')}</div>`}
function render(tab){document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 if(tab==='site')editor.innerHTML=`<div class="admin-title"><p>HOME</p><h1>Portada</h1><span>Editá lo que ve el público sin tocar código.</span></div><div class="form-grid">${input('Anuncio superior','site.announcement',data.site.announcement)}${input('Eyebrow','site.heroEyebrow',data.site.heroEyebrow)}${input('Título','site.heroTitle',data.site.heroTitle,'textarea')}${input('Descripción','site.heroText',data.site.heroText,'textarea')}${input('Imagen hero (URL o ruta)','site.heroImage',data.site.heroImage)}${input('Botón principal','site.heroPrimary',data.site.heroPrimary)}${input('Botón secundario','site.heroSecondary',data.site.heroSecondary)}</div>`;
 if(tab==='courses')editor.innerHTML=`<div class="admin-title"><p>CURSOS</p><h1>Oferta académica</h1><span>Texto, estado, brochure e imagen de cada curso.</span></div><div class="repeat-list">${data.courses.map((c,i)=>`<details class="edit-card" ${i===0?'open':''}><summary><b>${esc(c.title)} ${esc(c.subtitle)}</b><span>${esc(c.status)}</span></summary><div class="form-grid">${input('Título',`courses.${i}.title`,c.title)}${input('Subtítulo',`courses.${i}.subtitle`,c.subtitle)}${input('Eyebrow',`courses.${i}.eyebrow`,c.eyebrow)}${input('Duración',`courses.${i}.duration`,c.duration)}${input('Modalidad',`courses.${i}.mode`,c.mode)}${input('Requisito',`courses.${i}.requirement`,c.requirement)}${input('Estado',`courses.${i}.status`,c.status)}${input('Imagen 1600×1000',`courses.${i}.image`,c.image)}${input('Texto corto',`courses.${i}.short`,c.short,'textarea')}${input('Beneficio principal',`courses.${i}.benefit`,c.benefit,'textarea')}${input('URL brochure',`courses.${i}.brochure`,c.brochure)}</div></details>`).join('')}</div>`;
 if(tab==='testimonials')editor.innerHTML=repeatEditor('EXPERIENCIAS','Testimonios','testimonials',[{key:'name',label:'Nombre'},{key:'course',label:'Curso'},{key:'quote',label:'Testimonio',type:'textarea'},{key:'video',label:'URL video'},{key:'image',label:'Imagen / poster'}]);
 if(tab==='news')editor.innerHTML=repeatEditor('NOVEDADES','Novedades','news',[{key:'date',label:'Fecha'},{key:'tag',label:'Etiqueta'},{key:'title',label:'Título'},{key:'text',label:'Texto',type:'textarea'},{key:'link',label:'Enlace'},{key:'image',label:'Imagen'}]);
 if(tab==='services')editor.innerHTML=repeatEditor('SERVICIOS','Servicios','services',[{key:'eyebrow',label:'Categoría'},{key:'title',label:'Título'},{key:'text',label:'Texto',type:'textarea'},{key:'cta',label:'CTA'},{key:'image',label:'Imagen'}]);
 if(tab==='community')editor.innerHTML=repeatEditor('COMUNIDAD','Comunidad','community',[{key:'label',label:'Etiqueta'},{key:'title',label:'Título'},{key:'text',label:'Texto',type:'textarea'},{key:'link',label:'Enlace'},{key:'image',label:'Imagen'}]);
 if(tab==='settings')editor.innerHTML=`<div class="admin-title"><p>CONFIGURACIÓN</p><h1>Enlaces generales</h1></div><div class="form-grid">${input('WhatsApp','site.whatsapp',data.site.whatsapp)}${input('Instagram','site.instagram',data.site.instagram)}${input('Aula virtual','site.aula',data.site.aula)}${input('Red de Actores','site.actores',data.site.actores)}${input('Red de Realizadores','site.realizadores',data.site.realizadores)}${input('Dirección','site.location',data.site.location)}</div><div class="admin-warning"><b>Publicación protegida</b><p>Los cambios se guardan en Supabase. La web puede leerlos públicamente, pero solo las cuentas incluidas en <code>site_admins</code> pueden modificarlos.</p></div>`;bind()}
document.querySelectorAll('.admin-nav button').forEach(b=>b.onclick=()=>render(b.dataset.tab));
document.getElementById('saveBtn').onclick=async()=>{const b=document.getElementById('saveBtn');b.disabled=true;b.textContent='Publicando…';const {error}=await client.from('site_content').upsert({id:'main',content:data,updated_at:new Date().toISOString()});b.disabled=false;b.textContent=error?'Error al publicar':'Publicado ✓';setTimeout(()=>b.textContent='Publicar cambios',1600)};
document.getElementById('logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};init();
