(async function(){
  const defaults=structuredClone(window.CC_DEFAULT_CONTENT);
  let content=defaults;
  const cfg=window.CC_SUPABASE_URL&&window.CC_SUPABASE_ANON_KEY;
  if(cfg&&window.supabase){
    try{const client=window.supabase.createClient(window.CC_SUPABASE_URL,window.CC_SUPABASE_ANON_KEY);const {data,error}=await client.from('site_content').select('content').eq('id','main').maybeSingle();if(!error&&data?.content)content=deepMerge(defaults,data.content);}catch(e){}
  }
  window.CC_CONTENT=content; render(content);
  function deepMerge(target,source){if(Array.isArray(source))return source;if(source&&typeof source==='object')Object.keys(source).forEach(k=>{if(source[k]&&typeof source[k]==='object'&&!Array.isArray(source[k]))target[k]=deepMerge(target[k]||{},source[k]);else target[k]=source[k]});return target}
  function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
  function render(content){const site=content.site;document.querySelectorAll('[data-site]').forEach(el=>{const k=el.dataset.site;if(site[k]!=null)el.textContent=site[k]});document.querySelectorAll('[data-href-site]').forEach(el=>{const k=el.dataset.hrefSite;if(site[k])el.href=site[k]});document.querySelector('#hero-title').innerHTML=esc(site.heroTitle).replace(/\n/g,'<br>');document.querySelector('#hero-photo').src=site.heroImage||'assets/sample-photo.jpg';
    document.querySelector('#course-grid').innerHTML=[...content.courses].sort((a,b)=>a.order-b.order).map((c,i)=>`<a class="course-card ${c.featured?'featured':''}" href="course.html?c=${encodeURIComponent(c.slug)}"><div class="course-visual"><img class="card-photo" src="${esc(c.image||'assets/sample-photo.jpg')}" alt=""><div class="course-overlay"></div><span class="course-index">${String(i+1).padStart(2,'0')}</span><span class="course-status">${esc(c.status)}</span><span class="focus-corner"></span></div><div class="course-body"><p class="eyebrow">${esc(c.eyebrow)}</p><h3>${esc(c.title)}${c.subtitle?`<em>${esc(c.subtitle)}</em>`:''}</h3><p class="course-benefit">${esc(c.benefit)}</p><div class="course-meta"><span>${esc(c.duration)}</span><span>${esc(c.mode)}</span></div><div class="course-footer"><span>${esc(c.requirement)}</span><b>Ver curso ↗</b></div></div></a>`).join('');
    document.querySelector('#testimonial-grid').innerHTML=content.testimonials.map(t=>`<article class="testimonial-card ${t.featured?'testimonial-featured':''}"><div class="testimonial-media"><img src="${esc(t.image||'assets/sample-photo.jpg')}" alt=""><span class="play">▶</span><span class="video-label">TESTIMONIO</span></div><div class="testimonial-copy"><small>${esc(t.course)}</small><blockquote>“${esc(t.quote)}”</blockquote><p>${esc(t.name)}</p></div></article>`).join('');
    document.querySelector('#news-grid').innerHTML=content.news.map((n,i)=>`<a class="news-card ${i===0?'news-featured':''}" href="${esc(n.link)}"><div class="news-thumb"><img src="${esc(n.image||'assets/sample-photo.jpg')}" alt=""></div><div class="news-date">${esc(n.date)}</div><small>${esc(n.tag)}</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><b>Leer más ↗</b></a>`).join('');
    document.querySelector('#services-grid').innerHTML=content.services.map((s,i)=>`<article class="service-card"><div class="service-photo"><img src="${esc(s.image||'assets/sample-photo.jpg')}" alt=""></div><span class="service-no">0${i+1}</span><small>${esc(s.eyebrow)}</small><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><a href="https://wa.me/54${esc(site.whatsapp)}" target="_blank" rel="noopener">${esc(s.cta)} ↗</a></article>`).join('');
    document.querySelector('#community-grid').innerHTML=content.community.map(c=>`<a class="community-card" href="${esc(c.link)}"><div class="community-photo"><img src="${esc(c.image||'assets/sample-photo.jpg')}" alt=""></div><small>${esc(c.label)}</small><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><b>Explorar ↗</b></a>`).join('');
  }
  const menu=document.querySelector('.menu-button'),nav=document.querySelector('.nav');if(menu&&nav)menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)};
})();
